add headers
StratusGrid/terraform-github-repository-creation pull request #20
Opened 2024-04-05 11:11 UTC by JoseMotto-sg

## Change description

Repository header update. Note that this repo doesn't have terraform-docs, so only header is updated

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> Fix [#1](No Applicable) 

## Checklists

### Development

- [x] Lint rules pass locally
- [x] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [x] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2024-04-05 14:23 UTC, fernandoPedraza-sg requested changes

2024-04-09 10:22 UTC, JoseMotto-sg commented on .config/.terraform-docs.yml
>    # terraform-github-repository-creation
done

2024-04-09 14:27 UTC, fernandoPedraza-sg requested changes

2024-04-09 14:27 UTC, fernandoPedraza-sg commented on .config/header.md
> +<p align="center">                                                                                                                                            ─╯
```suggestion
<p align="center">                                                                                                                                        ```
@JoseMotto-sg, please remove spaces and text character at the end of this line.

2024-04-10 20:34 UTC, jheison-rodriguez requested changes

2024-04-10 20:34 UTC, jheison-rodriguez commented on .config/header.md
> +    <a href="https://stratusgrid.com/book-a-consultation">Contact Us Test</a> |
Remove ` Test`

2024-04-10 20:34 UTC, jheison-rodriguez commented on README.md
> +    <a href="https://stratusgrid.com/book-a-consultation">Contact Us Test</a> |
Remove ` Test`

2024-04-11 09:47 UTC, JoseMotto-sg commented on .config/header.md
> +    <a href="https://stratusgrid.com/book-a-consultation">Contact Us Test</a> |
Please open a suggestion directly

2024-04-11 09:47 UTC, JoseMotto-sg commented on README.md
> +    <a href="https://stratusgrid.com/book-a-consultation">Contact Us Test</a> |
Please open a suggestion directly

2024-04-11 13:38 UTC, jheison-rodriguez requested changes

2024-04-11 13:38 UTC, jheison-rodriguez commented on .config/header.md
> +    <a href="https://stratusgrid.com/book-a-consultation">Contact Us Test</a> |
```suggestion
    <a href="https://stratusgrid.com/book-a-consultation">Contact Us</a> |
```

2024-04-11 13:38 UTC, jheison-rodriguez commented on README.md
> +    <a href="https://stratusgrid.com/book-a-consultation">Contact Us Test</a> |
```suggestion
    <a href="https://stratusgrid.com/book-a-consultation">Contact Us</a> |
```

2024-04-11 20:36 UTC, closed without merging